USE hotel_management;

CREATE TABLE room_booking (
    id INT AUTO_INCREMENT PRIMARY KEY,
    room_number VARCHAR(50),
    check_in_date DATE,
    check_out_date DATE,
    check_in_time TIME,
    guest_name VARCHAR(100),
    age INT,
    customer_id VARCHAR(100),
    male_count INT,
    female_count INT,
    child_count INT,
    company VARCHAR(100),
    company_address VARCHAR(255),
    email VARCHAR(100),
    address VARCHAR(255),
    state VARCHAR(50),
    country VARCHAR(50),
    company_phone VARCHAR(15),
    customer_phone VARCHAR(15),
    payment_type VARCHAR(50),
    amount DECIMAL(10,2),
    discount DECIMAL(10,2),
    gst_percentage DECIMAL(5,2),
    total_price DECIMAL(10,2),
    advance_amount DECIMAL(10,2),
    id_proof_type VARCHAR(50),
    id_proof_number VARCHAR(50),
    segment VARCHAR(50),
    instructions TEXT,
    regular_customer BOOLEAN DEFAULT 0
);
